### ISSUE TITLE
ENH: Add changelog.md and track changes

### ISSUE THREAD

**Issue by corneliusroemer** [pycompression/xopen#115]

**Comment by marcelm** [comment]
The changelog is currently within the README: https://github.com/pycompression/xopen/blob/main/README.rst#changes

Do you need a separate page?

**Comment by corneliusroemer** [comment]
Oh, I missed that, was searching for changelog and couldn't find anything. Sorry for that.

**Comment by marcelm** [comment]
I’ve renamed the section to "Changelog". The consequence is that the above link doesn’t work anymore, it’s now https://github.com/pycompression/xopen/blob/main/README.rst#changelog.
