### ISSUE TITLE
ENH: Make new release to allow usage of zstd

### ISSUE THREAD

**Issue by corneliusroemer** [pycompression/xopen#116]

**Comment by marcelm** [comment]
We were waiting for the python-zstandard author to get back to us regarding the wheel size because it would be nicer to not have zstd as an optional dependency (but as a regular dependency instead). It’s been ten days, so let’s go with the optional dependency.

I’ll make a release tomorrow.

**Comment by marcelm** [comment]
Version 1.7.0 is now available on PyPI. The conda-forge package will probably also be available later today.
