### ISSUE TITLE
xopen does not support .zst file compressed with Zstandard long memory mode 

### ISSUE THREAD

**Issue by gcflymoto** [pycompression/xopen#155]
When compressing a file with long memory mode

`zstd -T4 -9 --force --rm --exclude-compressed --no-progress --long=31 file.txt`

Xopen cannot decode it
```
python3 -c 'import xopen; f = xopen.xopen("file.txt.zst"); f.readline()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
zstd.ZstdError: zstd decompress error: Frame requires too much memory for decoding
```

```
zstd -vl file.txt.zst
*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***
tmpz/ip2ip_final.rpt.zst 
# Zstandard Frames: 1
DictID: 0
Window Size: 1.18 GiB (1264573175 B)
Compressed Size: 27.6 MiB (28914291 B)
Decompressed Size: 1.18 GiB (1264573175 B)
Ratio: 43.7352
Check: XXH64 d5d984dc
```
It seems the way to address this is [here in the lower level zstandard library](https://stackoverflow.com/questions/69270987/how-to-resolve-the-error-related-to-frame-used-in-zstandard-which-requires-too-m).

**Comment by rhpvorderman** [comment]
The solution is mentioned as `zstdDecompressor(max_window_size=2147483648)`

That is effectively a 2GiB window size, meaning every zst file opened will use 2 GiB. That is going to lead to Out-Of-Memory (OOM) issues. Especially on cluster HPC systems were memory needs to be requested beforehand.
I see you compress with the `--long=31` flag. I take this means 31 bits of window size. That is quite big. I see from your zstandard CLI output that this leads to the entire file being considered into one window.

I did some research and I see that the standard limit for zstandard is 27 bits: https://github.com/facebook/zstd/blob/78f732cfdd65bccc76d7da2ae103e141e5ca5742/lib/zstd.h#L1250 . 

So what we can do at xopen is override this limit with a bigger limit like you suggest. But that also is a limit, so technically it does not solve this "bug". When a file comes along with an even larger window size, that will not decompress either. Allowing unlimited windowsizes is a bad idea IMHO, so we should stick to some limit. It is much easier to stick to the library default which is 27 bits.

What is the use case for compression windows that are larger than the file itself? Who produces these files?

**Comment by gcflymoto** [comment]
> much better does the compression actually get when you use --long=31 instead of the default (--long=27)?

It can be substantial on multi-GB files of certain datasets.

Another alternative to an xopen parameter could be check the .zst file for the window size and "right size" Zstd's decompressor window size only when needed.

**Comment by marcelm** [comment]
> It can be substantial on multi-GB files of specific datasets.

Ok, so that means that this is a use case that is worth supporting.

> Another alternative to an xopen parameter could be to check the .zst file for the window size and "right size" Zstd's decompressor window size only when needed.

I thought about this as well, but always setting the max window size is simpler and has essentially the same effect since no additional memory is used anyway for files that use a smaller window size. I think I would prefer to have some hard-coded upper limit (at least until the next user files an issue ...), so the only question would be which limit to use. Maybe $2^{31}$ is enough for now.

**Comment by gcflymoto** [comment]
Oh by the way. Zstd only supports 2^31 as the maximum window size. I'm unsure if this should be set by default; wouldn't it cause every xopen to use 2GB?

**Comment by marcelm** [comment]
Ah, then we can just use $2^{31}$. 

> I'm unsure if this should be set by default; wouldn't it cause every xopen to use 2GB?

We would need to set this option only in the decompressor, not in the compressor. And for the decompressor, memory usage depends on what was used when the file was compressed.

Compression with default options needs ~13 MB RAM:
```
$ /usr/bin/time -f '%M KiB' zstd largefile.txt
largefile.txt        : 22.17%   (1952177590 => 432732941 bytes, largefile.txt.zst) 
38272 KiB
```
And decompression from Python uses ~13 MB, even with `max_window_size=2**31`:
``` 
$ /usr/bin/time -f '%M KiB' python -c 'import zstandard'$'\n''for _ in zstandard.open("largefile.txt.zst", mode="rt", dctx=zstandard.ZstdDecompressor(max_window_size=2**31)): pass'
12928 KiB
```

**Comment by rhpvorderman** [comment]
Excellent! I see that zstandard has a WINDOWLOG_MAX constant that is 31. 
I propose using that. I am glad that there is an upper limit, so my concerns about OOM don't materialize.

**Comment by rhpvorderman** [comment]
I made  a fix. The code change is not that big.

**Comment by gcflymoto** [comment]
Thanks!

**Comment by rhpvorderman** [comment]
@gcflymoto It should be installable with the 2.0.1 release.
