### ISSUE TITLE
xopen 2.0.0 does not read stdin fully

### ISSUE THREAD

**Issue by peterjc** [pycompression/xopen#157]
Originally logged as https://github.com/marcelm/cutadapt/issues/774 but reduced to an xopen only test case by @rhpvorderman :

```
(xopen) rhpvorderman@tuxminator:~/PycharmProjects/xopen$ pip list | grep xopen
xopen              2.0.0
(xopen) rhpvorderman@tuxminator:~/PycharmProjects/xopen$ wc -l ~/test/5millionreads_R1.fastq
20000000 /home/rhpvorderman/test/5millionreads_R1.fastq
(xopen) rhpvorderman@tuxminator:~/PycharmProjects/xopen$ cat ~/test/5millionreads_R1.fastq | python -c 'import xopen; f=xopen.xopen("/dev/stdin", "rt"); print(f.read())' | wc -l
19999956
(xopen) rhpvorderman@tuxminator:~/PycharmProjects/xopen$ cat ~/test/5millionreads_R1.fastq | python -c 'import xopen; f=xopen.xopen("-", "rt"); print(f.read())' | wc -l
19999956
(xopen) rhpvorderman@tuxminator:~/PycharmProjects/xopen$ pip install xopen==1.9.0 >/dev/null
(xopen) rhpvorderman@tuxminator:~/PycharmProjects/xopen$ cat ~/test/5millionreads_R1.fastq | python -c 'import xopen; f=xopen.xopen("-", "rt"); print(f.read())' | wc -l
20000001
(xopen) rhpvorderman@tuxminator:~/PycharmProjects/xopen$ cat ~/test/5millionreads_R1.fastq | python -c 'import xopen; f=xopen.xopen("/dev/stdin", "rt"); print(f.read())' | wc -l
20000001
(xopen) rhpvorderman@tuxminator:~/PycharmProjects/xopen$ 
```

The +1 is from print adding a new line.

**Comment by marcelm** [comment]
@rhpvorderman I guess yanking the release is indeed appropriate.

**Comment by marcelm** [comment]
Bisecting points to commit 76987fe28ecc5fd9c6c65e2f4be33c43388cc9d0

**Comment by peterjc** [comment]
Adding ``, end=""`` to the print function makes the example clearer.

Is it missing the final few lines of the input?

**Comment by marcelm** [comment]
It’s missing the first 64 kB I believe. I think what happens is that this `peek()` reads the first 64 kB from stdin and then something happens such that these 64 kB are skipped when the data is actually read

https://github.com/pycompression/xopen/blob/bc9e899a67bb9c284916485ceadaa6e1768f9c51/src/xopen/__init__.py#L650

@rhpvorderman I yanked the release and need to go now. Now it’s less urgent, but can you look into this?

**Comment by rhpvorderman** [comment]
Yes. The peek is not the issue.
The problem is that "/dev/stdin" is opened multiple times. Once in the detection and once elsewhere. This causes the issue. I will look into a fix,

**Comment by rhpvorderman** [comment]
Made a PR and a whole lot of tests. We may still break a lot of other things, but not this particular thing anymore ;-).

**Comment by rhpvorderman** [comment]
@peterjc, could you verify that the PR branch fixes your cutadapt problems?

**Comment by rhpvorderman** [comment]
I just checked, and it works again! I will release 2.0.1

**Comment by peterjc** [comment]
Confirming my original test case passes with the current cutadapt release and xopen from github. Thank you.

**Comment by rhpvorderman** [comment]
Thanks for reporting the bug and providing test data!
