### ISSUE TITLE
Unable to use xopen handle as output of subprocess (`io.UnsupportedOperation: fileno`)

### ISSUE THREAD

**Issue by victorlin** [pycompression/xopen#162]
My goal is to run a shell command and stream the output to a compressed file. I figured xopen would be a good way to achieve this, however I can't get it to work. Here is a minimal reproducible example:

```py
from xopen import xopen
from subprocess import run

with xopen("file1.txt", "w") as f:
    f.write("something")

with xopen("file2.txt.xz", "wb") as f:
    run(["cat", "file1.txt"], stdout=f)
    # also tried:
    # • Popen(["cat", "file1.txt"], stdout=f)
    # • call(["cat", "file1.txt"], stdout=f)
    # • output file extension of .gz, .zst
```

Error:

```
  File "test.py", line 8, in <module>
    run(["cat", "file1.txt"], stdout=f)
  File "…/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "…/python3.10/subprocess.py", line 837, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "…/python3.10/subprocess.py", line 1638, in _get_handles
    c2pwrite = stdout.fileno()
io.UnsupportedOperation: fileno
```

An alternative is to use `check_output`, but I would like to do this without storing the subprocess output in memory since it may be large.

```py
# This works but output is stored in memory
output = check_output(["cat", "file1.txt"])
with xopen("file2.txt.xz", "wb") as f:
    f.write(output)
```

Questions:

1. Is there a way to achieve my goal with other subprocess functions/parameters?
2. If not, are there plans to support this in xopen?

**Comment by rhpvorderman** [comment]
2. No, because it fundamentally does not work. Subprocess needs to write to a file descriptor that exists in the kernel. (That is basically the fileno). Python user space objects such as xopen custom classes (or gzip, or whatever else) do not exist in the kernel. 

1. Yes, there is a workaround. In fact I run into the same problem in xopen once where I was not able to set an input for stdin. So I wrote a function that runs in a separate thread that reads from my input file and writes to the process stdin.  In your case what you can do is the following pattern:

```python3
with xopen("file2.txt.xz", "wb") as f:
    process = Popen(["cat", "file1.txt"], stdout=subprocess.PIPE)
    stdout_file = process.stdout
    while True:
        chunk = stdout_file.read(128 * 1024)
        if not chunk:
            break
        f.write(chunk)
   process.wait()
   # process error checking goes here
   ```
That way not the whole file is stored in memory.

**Comment by victorlin** [comment]
@rhpvorderman thank you for the helpful response! I'll close this as "not planned".

**Comment by victorlin** [comment]
Another workaround is to use `shutil.copyfileobj`:

```py
with xopen("file2.txt.xz", "wb") as f:
    process = Popen(["cat", "file1.txt"], stdout=PIPE)
    copyfileobj(process.stdout, f, 128 * 1024)
    process.wait()
   # process error checking goes here
```

Credits to @tsibley who pointed me in this direction with his work in https://github.com/nextstrain/augur/pull/1562

**Comment by rhpvorderman** [comment]
Oh yes. Thanks @victorlin . I am so used to writing these little while loops that I forget that the copyfileobj function does that automatically.
