### ISSUE TITLE
New reproducibility option in python 3.8

### ISSUE THREAD

**Issue by rhpvorderman** [pycompression/xopen#26]
https://docs.python.org/3/whatsnew/3.8.html#gzip

If at some point bit-for-bit reproducible output files are needed we might want to use this.

Also I believe pigz can do this with the `-m` and `-n` flags.

**Comment by marcelm** [comment]
That particular added feature was specifically for `gzip.compress`. We need `gzip.GzipFile` and can use its `mtime` and `filename` parameters that even exist in earlier Python versions.
