### ISSUE TITLE
Using python-isal to speed up gzip compression/decompression without relying on pipes.

### ISSUE THREAD

**Issue by rhpvorderman** [pycompression/xopen#37]
Hi,

This is the project I have been working on: https://github.com/rhpvorderman/python-isal. It creates python bindings for the [isa-l library](https://github.com/intel/isa-l). It provides zlib and gzip-compatible modules. This can speed up compression and decompression quite a bit and it does not need pipes.

It is not production ready at this moment. I still need to integrate a full test suite based on the zlib/gzip tests from CPython, so that I at least cover a wide range of production use cases. I will start working on that soon, but as mentioned earlier I may not be able to finish that work before I will be offline for quite a while.

I will be almost continuously working on this to get it into shape and release a first version.

**Comment by rhpvorderman** [comment]
Hi. I moved python-isal to its own organization `pycompression` so it will be independent of my current organization (LUMC) and my personal github account. It is now here: https://github.com/pycompression/python-isal

I also made the first release  0.1.0. It uses all the CPython tests for the gzip and zlib modules. While the zlib module still has some issues, **the isal.igzip module is fully compliant with CPython's gzip module tests**. So this can be used now relatively safely in production.

I can build this into xopen. @marcelm I am thinking to making isal usage optional, since the compression levels when writing lead to different output sizes. So adding a `use_isal` keyword argument to the `xopen` function. This can later be extended to cutadapt as well with a `--use-isal` so people at least know what's happening, it can also be added to the `-Z` flag. 
The current situation with isal being determined by compression level and availability can lead to inconsistent/unpredictable behaviour. What do you think?

**Comment by marcelm** [comment]
Cool, and congratulations on the first release!

For decompression, is it correct that there aren’t any downsides to using ISA-L? It is just faster, right? So then it should always be used if it’s available. For compression, if the same compression level leads to only slightly bigger files, then I’d lean towards making it the default if it is available. One idea with xopen is to use the fastest option available, so that would be an argument in favor. And it’s actually already the case that the output is different depending on whether `igzip`, `pigz` or `gzip` is used.

How big are the differences in compressed size again, compared to regular gzip? I believe you had an issue or PR somewhere with a table, but I cannot find it at the moment.

**Comment by marcelm** [comment]
BTW, I would be open to moving xopen into the pycompression organization if you’re interested.

**Comment by rhpvorderman** [comment]
> How big are the differences in compressed size again, compared to regular gzip? I believe you had an issue or PR somewhere with a table, but I cannot find it at the moment.

Igzip sizes are smaller at the low compression levels I believe. https://github.com/marcelm/cutadapt/issues/425#issuecomment-658239834 in that post it is 657M for zlib/gzip level 1 and 619M for igzip level 1 (and 598M for zlib/gzip level 5).

 > For decompression, is it correct that there aren’t any downsides to using ISA-L? It is just faster, right? So then it should always be used if it’s available. 

It should always be faster, barring very small files when python-isal is used. The igzip module inherits the gzip module, and therefore it requires some extra setup time for the IGzipFile object vs the GzipFile object. Hence igzip.open is slightly slower for very small files (I can't remember but somewhere around 32-64KB this is already negated by the extra speed).

> BTW, I would be open to moving xopen into the pycompression organization if you’re interested.

That would be great. I am also fine with leaving it as it is now. I follow your lead here, since it is your project. But I do think that moving these sort of projects under the pycompression umbrella will provide a nice space for python+compression enthusiasts to cooperate on projects. I will go ahead and make you an owner of the pycompression project.

It would require changing the homepage in setup.py and on the conda recipe as well, by the way. I forgot to do this so python-isal 0.1.0 still refers to rhpvorderman/python-isal on pypi :man_facepalming: .

**Comment by marcelm** [comment]
I think we can close this, right? I moved the repo now, which was the only reason for me to still have this issue open.
