### ISSUE TITLE
Replace pigz with python-isal where possible

### ISSUE THREAD

**Issue by rhpvorderman** [pycompression/xopen#48]
Hi!

I was thinking about the weird dichotomy we have created. When you use multiple threads with xopen `pigz` will be used if `igzip` is not installed. Lately we have added python-isal support. This only works on one thread, but it is waaaaay more efficient than `pigz` in terms of compute time needed. On the other hand, this time is spent *inside* the python GIL. A disadvantage which pigz does not have. 
So when using multiple threads, pigz will be faster (if a low compression level is used) in wall clock time, but not in total cpu hours.

What to do about this? I didn't know. Then I realized that `python -m gzip` is a functional command. And that this behavior is also present in `python -m isal.igzip` (it's a complete drop-in replacement!). Unlike `python -m gzip` which uses a crazy buffer size of 1K (Idiocy! I should make a PR rectifying this). `python -m isal.igzip` uses `_compression.DEFAULT_BUFFER_SIZE` (8K on my system). It has piping capability. 

Check this out:

compression using pipes (similar to how xopen offloads processes)
```
$ hyperfine -w 2 -r 5 'cat big2.fastq | pigz -1 -p 1 > ramdisk/big2.fastq.gz'
Benchmark #1: cat big2.fastq | pigz -1 -p 1 > ramdisk/big2.fastq.gz
  Time (mean ± σ):     22.289 s ±  0.140 s    [User: 21.676 s, System: 0.849 s]
  Range (min … max):   22.174 s … 22.529 s    5 runs
 
$ hyperfine -w 2 -r 5 'cat big2.fastq | python -m isal.igzip -1 > ramdisk/big2.fastq.gz'
Benchmark #1: cat big2.fastq | python -m isal.igzip -1 > ramdisk/big2.fastq.gz
  Time (mean ± σ):      5.378 s ±  0.067 s    [User: 4.960 s, System: 0.992 s]
  Range (min … max):    5.294 s …  5.480 s    5 runs
 
$ hyperfine -w 2 -r 5 'cat big2.fastq | igzip -1 > ramdisk/big2.fastq.gz'
Benchmark #1: cat big2.fastq | igzip -1 > ramdisk/big2.fastq.gz
  Time (mean ± σ):      4.881 s ±  0.037 s    [User: 4.280 s, System: 0.775 s]
  Range (min … max):    4.861 s …  4.947 s    5 runs
```

Decompression using pipes
```
$ hyperfine -w 2 -r 5 'cat big2.fastq.gz | pigz -d -p 1 > ramdisk/big2.fastq'
Benchmark #1: cat big2.fastq.gz | pigz -d -p 1 > ramdisk/big2.fastq
  Time (mean ± σ):      6.644 s ±  0.020 s    [User: 6.269 s, System: 0.584 s]
  Range (min … max):    6.629 s …  6.680 s    5 runs
 
$ hyperfine -w 2 -r 5 'cat big2.fastq.gz | python -m isal.igzip -d  > ramdisk/big2.fastq'
Benchmark #1: cat big2.fastq.gz | python -m isal.igzip -d  > ramdisk/big2.fastq
  Time (mean ± σ):      4.473 s ±  0.022 s    [User: 3.912 s, System: 0.843 s]
  Range (min … max):    4.454 s …  4.506 s    5 runs
 
$ hyperfine -w 2 -r 5 'cat big2.fastq.gz | igzip -d  > ramdisk/big2.fastq'
Benchmark #1: cat big2.fastq.gz | igzip -d  > ramdisk/big2.fastq
  Time (mean ± σ):      3.414 s ±  0.030 s    [User: 2.835 s, System: 0.634 s]
  Range (min … max):    3.377 s …  3.451 s    5 runs
```

So if `igzip` is NOT installed (very likely) using  `python -m isal.igzip` is the fastest way on systems where python-isal is installed (100% guaranteed on linux and mac).

Are you thinking what I am thinking? `git checkout -b MOARRRPERFORMANCE1!1!` :rocket:

**Comment by marcelm** [comment]
Just wanted to let you know that I have looked at this today and I think it sounds good, but I need to think this through a bit more because I’m not so sure that the GIL is actually such a big problem. Perhaps it would be fine (at least for Cutadapt) to just not use any external processes when python-isal is available.

Hm, I’ve lost a bit track of what xopen does under which circumstances. Perhaps we should add some debug logging.

**Comment by rhpvorderman** [comment]
Yes. I think it depends on how much of your workload is actually compression. If it less than x% it might not significantly blocking enough to warrant launching an external process. (Don't know the x-factor here).
Regardless, `python -m isal.igzip` is always faster than pigz (especially when decompressing), so when an external process is launched, it better be  the faster one.
