### ISSUE TITLE
Fallback code when isal unavailable is not tested

### ISSUE THREAD

**Issue by marcelm** [pycompression/xopen#58]
#57 reduced the test coverage, and we need to fix this.

The `isal` module is now always imported succesfully in all test configurations.

My suggestion is to
1. change `if igzip is not None` to `if "isal" not in sys.modules`,
2. and use [pytest.monkeypatch](https://docs.pytest.org/en/stable/monkeypatch.html) to temporarily remove the `isal` module from `sys.modules` during a test, forcing use of the fallback code.

**Comment by rhpvorderman** [comment]
First I am going to benchmark performance. It occurred to me that PyPy may have different performance characteristics for a cython build extension.

**Comment by rhpvorderman** [comment]
Testing performed using conda python 3.9 and conda pypy37. With conda python-isal. These are all compiled with similar settings, so there is no compilation bias. (Using system-compiled python with local-compiled isal is not so great for these comparisons I think).
Input will be a 500,000 read fastq file.

The test scripts:

decomp_gzip.py
```
#!/usr/bin/env python3

import sys
import gzip

with gzip.open(sys.argv[1]) as file_h:
    while True:
        block = file_h.read(64*1024)
        if block == b"":
            break
```

decomp_igzip.py
```
#!/usr/bin/env python3

import sys
from isal import igzip

with igzip.open(sys.argv[1]) as file_h:
    while True:
        block = file_h.read(64*1024)
        if block == b"":
            break
```

## Benchmarks.

Pypy using stdlib gzip:
```
Benchmark #1: ./decomp_gzip.py 500000reads.fastq.gz
  Time (mean ± σ):      1.871 s ±  0.223 s    [User: 1.838 s, System: 0.016 s]
  Range (min … max):    1.484 s …  2.137 s    10 runs
```
Pypy using python-isal
```
Benchmark #1: ./decomp_igzip.py 500000reads.fastq.gz
  Time (mean ± σ):      1.552 s ±  0.137 s    [User: 1.513 s, System: 0.022 s]
  Range (min … max):    1.394 s …  1.793 s    10 runs
```

CPython using stdlib gzip
```
Benchmark #1: ./decomp_gzip.py 500000reads.fastq.gz
  Time (mean ± σ):     702.2 ms ±   4.9 ms    [User: 693.0 ms, System: 8.9 ms]
  Range (min … max):   693.3 ms … 707.1 ms    10 runs
```

CPython using python-isal:
```
Benchmark #1: ./decomp_igzip.py 500000reads.fastq.gz
  Time (mean ± σ):     355.0 ms ±   3.3 ms    [User: 335.9 ms, System: 18.8 ms]
  Range (min … max):   350.7 ms … 362.8 ms    10 runs
```

Conclusion. PyPy **sucks** (Q.E.D.) . But it sucks slightly less with python-isal.

**Comment by rhpvorderman** [comment]
```
My suggestion is to

    change if igzip is not None to if "isal" not in sys.modules,
    and use pytest.monkeypatch to temporarily remove the isal module from sys.modules during a test, forcing use of the fallback code.
```
Alternatively: monkeypatch igzip to be None? Same results probably..  Or use `"isal.igzip in sys.modules"`. `import isal` does not execute code (well, only some version constants are loaded). While `from isal import igzip` executes code, including `from isal import isal_zlib`. 

I will try something. It should be doable.
