### ISSUE TITLE
bz2 speed improvements

### ISSUE THREAD

**Issue by marcelm** [pycompression/xopen#62]
We should consider some of the suggestions made at https://bugs.python.org/issue43785 and discussed at https://discuss.python.org/t/6869/8

**Comment by DriesSchaumont** [comment]
@marcelm mentionning PR #63  here. Although needs some tests.

**Comment by rhpvorderman** [comment]
Hmm I guess with #63 implemented and the core python code base implementing a faster BZ2 reader (available from 3.10?) this issue can be closed. Thanks again @DriesSchaumont
