### ISSUE TITLE
`f.read(0)` seems to wait forever

### ISSUE THREAD

**Issue by zhangrengang** [pycompression/xopen#68]
The following code will do nothing except wait:
```
f = xopen('xxx.gz')
f.read(0)
```

**Comment by rhpvorderman** [comment]
I cannot reproduce this error. Was this closed because it was fixed?

**Comment by zhangrengang** [comment]
Yes, update make it works. I installed xopen by conda, but it did not install the lastest one.

**Comment by rhpvorderman** [comment]
Okay, that is good to hear. Thank you for getting back to us.
