### ISSUE TITLE
Issue in use of PEP 508 environment markers

### ISSUE THREAD

**Issue by jezdez** [pycompression/xopen#70]
https://github.com/conda/conda/issues/10907 has reported an issue in conda that is triggered by a wrong use of PEP 508 environment markers in xopen, in the case of the metadata of the version of xopen as reported in the ticket (1.1.0) it was:

```
isal (>=0.3.0) ; sys_platform=="linux" and python_implementation != "PyPy"'
```

PEP 508 lists the [valid names of environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) and `python_implementation` isn't one of them, correct would be `platform_python_implementation`.

Looking at the setup.py this seems to have changed recently to be:

https://github.com/pycompression/xopen/blob/e9cb17c969aacab7d4c08c9e313609bf14b9fc5e/setup.py#L21-L28

Which again uses the wrong name for the environment marker, it should be:

```
        # Install isa-l on 64 bit platforms. Python-isal wheels are provided for:
        # x86_64: Linux and MacOS x86_64 platforms
        # AMD64: Windows x86_64 platforms.
        # aarch64: Linux ARM 64-bit platforms.
        # Wheels are not provided for 'arm64'. The MacOS 64 bit platforms. 
        ':platform_machine == "x86_64"': ['isal>=0.9.0'],
        ':platform_machine == "AMD64"': ['isal>=0.9.0'],
        ':platform_machine == "aarch64"': ['isal>=0.9.0'],
```

**Comment by marcelm** [comment]
Thanks for reporting! I have fixed this now. Are you possibly aware of any linters that check whether the used environment markers are allowed? A check search hasn’t turned up anything.

I’ll release a new version of xopen as well; that has been long overdue anyway.

**Comment by jezdez** [comment]
I'm not sure, I thought wheel would check the markers to be honest, but I'm now wondering if you using `extras_require` instead of `install_requires` would trigger this since the use of `extras_require` has been deprecated a long time ago.

I would suggest to update your `setup.py` to follow the pattern as [shown in the setuptools docs](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=508#platform-specific-dependencies) (select the setup.py tab in the code example).

```python
setup(
    name='xopen',
    use_scm_version={'write_to': 'src/xopen/_version.py'},
    setup_requires=['setuptools_scm'],  # Support pip versions that don't know about pyproject.toml
    author='Marcel Martin et al.',
    author_email='mail@marcelm.net',
    url='https://github.com/pycompression/xopen/',
    description='Open compressed files transparently',
    long_description=long_description,
    license='MIT',
    package_dir={'': 'src'},
    packages=find_packages('src'),
    package_data={"xopen": ["py.typed"]},
    install_requires=[
        # Install isa-l on 64 bit platforms. Python-isal wheels are provided for:
        # x86_64: Linux and MacOS x86_64 platforms
        # AMD64: Windows x86_64 platforms.
        # aarch64: Linux ARM 64-bit platforms.
        # Wheels are not provided for 'arm64'. The MacOS 64 bit platforms. 
        'isal>=0.9.0; platform_machine=="x86_64" or platform_machine=="AMD64" or platform_machine=="aarch64"'
    ]
    extras_require={
        'dev': ['pytest'],
    },
    python_requires='>=3.6',
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
    ]
)
```

**Comment by marcelm** [comment]
Indeed, specifying that [seems to be outdated syntax](https://hynek.me/articles/conditional-python-dependencies/#extras_require) necessary for old setuptools versions.

While I’m at it, I’ll also switch to using a `setup.cfg`.

**Comment by marcelm** [comment]
I’m not quite sure how to interpret [this discussion](https://discuss.python.org/t/can-extras-require-values-be-os-dependant)/2718/4), but it appears that pip has some aliases and thus also understands both `python_implementation` and `platform.machine`. But I would think that that’s nonstandard and not quite PEP-compliant.
