### ISSUE TITLE
Test failure in test_truncated_with

### ISSUE THREAD

**Issue by marcelm** [pycompression/xopen#72]
This test appears to fail sporadically for the `bz2` case (and length 1024):
https://github.com/pycompression/xopen/runs/3636266596?check_suite_focus=true

https://github.com/pycompression/xopen/blob/7c2518bcedbd6a876d572339ac619384b80332d5/tests/test_xopen.py#L467-L473

I’m trying to reproduce it locally with `while pytest tests/test_xopen.py::test_truncated_with; do : ; done`, but haven’t succeeded.

**Comment by marcelm** [comment]
I was able to reproduce this now somewhat reliabley with `stress` running on a separate terminal, and to find what the problem is.

This happens with `pbzip2` installed, that is, with a `PipedPBzip2Reader`.

Normally, when `PipedCompressionReader.close()` is called after an error (because of the truncated input file), the process has already ended, and the message written on stderr is:
```
pbzip2: *ERROR: File ends unexpectedly!  Skipping...

 exit requested - quitting...
```

However, when the process is still running during `close()`, then `terminate()` is used to end it. In that case, the output on stderr is:
```
pbzip2: *ERROR: File ends unexpectedly!  Skipping...

 *Control-C or similar caught [sig=15], quitting...
Terminator thread: premature  quitting...
```
So there’s the error message *and* the Control-C message in the output. We then see that the output contains the `Control-C or similar` message and decide that there was not actually an error:
https://github.com/pycompression/xopen/blob/223b5ed4ec700e026aab66ee44f092aa78051510/src/xopen/__init__.py#L372-L374

So the "File ends unexpectedly" message was ignored, and we don’t raise an error.

**Comment by rhpvorderman** [comment]
There is a difference between SIGTERM and SIGINTERRUPT though so we should be able to intercept that. I see the message catches sig=15 which is SIGTERM. We can fix this with some tweaking.
