### ISSUE TITLE
pbzip2 waits one second when input is empty

### ISSUE THREAD

**Issue by marcelm** [pycompression/xopen#89]
Runninng `pytest --durations=10`, I noticed that `test_xopen_has_iter_method` with ext=`.bz2` takes one second to complete, which is surprising because it only checks whether an instance of `PipedPBzip2CompressionWriter` has the `__iter__` attribute.

It turns out that `pbzip2` has a delay of 1 second when piping empty input into it.
```
$ time echo -n|pbzip2 > out.bz2

real    0m1.004s
user    0m0.000s
sys     0m0.005s
```
For the tests, this can be fixed by just writing some data into the process – then there’s no delay.

**Comment by rhpvorderman** [comment]
Haha I noticed that bz2 files were slow, but I figured that was because bzip2 was slow as hell anyway :smile: . Good find!
