### ISSUE TITLE
The tests for fallback to built-in functions do not quite work

### ISSUE THREAD

**Issue by marcelm** [pycompression/xopen#95]
We have this test (and some like it):
```python
def test_xopen_falls_back_to_gzip_open(lacking_pigz_permissions):
    with xopen(TEST_DIR / "file.txt.gz", "rb") as f:
        assert f.readline() == CONTENT_LINES[0].encode("utf-8")
```
This was fine as long as only `pigz` was supported as external tool, but nowadays, this falls back to one of the other tools that we support. We probably need to temporarily unset PATH entirely to properly test whether the fallback works.

**Comment by rhpvorderman** [comment]
Since all the external gzip programs are not used anymore except `pigz` and `gzip`, is this still an issue?

**Comment by marcelm** [comment]
Probably not, let’s just close this.
