### ISSUE TITLE
Support hooking into `xz` executable

### ISSUE THREAD

**Issue by fanninpm** [pycompression/xopen#98]
In https://github.com/pycompression/xopen/pull/32#pullrequestreview-441546816, it was decided that `xz` compression would not get its own `PipedCompressionReader` and `PipedCompressionWriter` subclasses for the time being. I would like to take advantage of `xz`'s multithreaded compression option, but there's currently no way to do that within xopen. Do you think this would be reasonable enough to add?

**Comment by rhpvorderman** [comment]
I do not have time to add this myself. But I will happily review a PR.

If you are comfortable writing Python code, it should be trivial to add support yourself and make that PR. 

If you look at the support for PipedPigzWriter, PipedPigzReader etc. (https://github.com/pycompression/xopen/blob/19b38dcc045d4442345a421046e53e981d899839/src/xopen/__init__.py#L517) then you should be able to figure it out. Also add a few tests to make sure it works.
